name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ make zlib1g-dev
        # Install ROOT
        sudo apt-get install -y dpkg-dev gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev
        sudo apt-get install -y root-system-bin root-system-common root-system-dev root-system-rootd root-system
        # Print ROOT version
        root-config --version

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    # Optional: Run tests if you have them
    # - name: Run tests
    #   run: ctest --test-dir build 