name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ make zlib1g-dev wget

    - name: Download and extract ROOT
      run: |
        wget https://root.cern/download/root_v6.36.00.Linux-ubuntu24.04-x86_64-gcc13.3.tar.gz
        echo "Untarring ROOT"
        tar -xzf root_v6.36.00.Linux-ubuntu24.04-x86_64-gcc13.3.tar.gz
        echo "Removing tar file"
        rm root_v6.36.00.Linux-ubuntu24.04-x86_64-gcc13.3.tar.gz
        echo "Adding ROOT to PATH"
        source root/bin/thisroot.sh
    

    - name: Configure CMake
      run: |
        ROOTDIR=$(pwd)/root
        cmake -S . -B build -DCMAKE_PREFIX_PATH=$ROOTDIR

    - name: Build
      run: cmake --build build

    # Optional: Run tests if you have them
    # - name: Run tests
    #   run: ctest --test-dir build 